theme: night
title: Mi filosofía del SL
revealjs_config:
  #  dependencies:
  #  - src: 'js/custom.js'
  history: true
    #  menu:
    #    side: left
    #    titleSelector: 'h1'
    #    hideMissingTitles: true
    #    themes: false
    #    openButton: true
# El menu se comenta porque no funciona el highlighting
